language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

before_script:
# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
  - composer install -n

# Explicitly use the phpunit from composer, not any system-wide found
script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml tests

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml
